apiVersion: apps/v1
kind: Deployment
metadata:
  name: home-sync
spec:
  replicas: 3
  selector:
    matchLabels:
      app: home-sync
  template:
    metadata:
      labels:
        app: home-sync
    spec:
      runtimeClassName: wasmtime-spin
      containers:
        - name: home-sync
          image: home-sync:0.1.0
          command: ["/"]
---
apiVersion: v1
kind: Service
metadata:
  name: home-sync
spec:
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  selector:
    app: home-sync
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: home-sync
  annotations:
    ingress.kubernetes.io/ssl-redirect: "false"
spec:
  ingressClassName: traefik
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: home-sync
                port:
                  number: 80
